#!/usr/bin/env node
// Generate a synthetic corpus and time the tool on it.
//
// The numbers in the README come from here, so they are reproducible rather than
// remembered. The corpus is shaped like a real docs set: frontmatter, headings,
// tables, code fences, images, links, an FAQ block, and one span map per document.

import { writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const dir = path.join(root, '.bench');
const bin = path.join(root, 'bin', 'groundtruth.mjs');
const count = Number(process.argv.find((arg) => /^\d+$/.test(arg)) || 200);

const WORDS = 'engine queue cache driver platform request buffer scheduler worker index shard replica token session cursor payload handler adapter registry pipeline'.split(' ');
const word = (i) => WORDS[i % WORDS.length];

function build() {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  mkdirSync(path.join(dir, 'docs'), { recursive: true });
  mkdirSync(path.join(dir, 'sources'), { recursive: true });
  mkdirSync(path.join(dir, 'groundtruth', 'spans'), { recursive: true });

  let words = 0;

  for (let d = 0; d < count; d += 1) {
    const id = String(d).padStart(4, '0');
    const held = (d * 7) % 512;
    const lines = [
      '---',
      `title: Document ${d} about the ${word(d)} subsystem`,
      `seo_title: The ${word(d)} subsystem, explained`,
      `slug: document-${d}-${word(d)}`,
      `primary_keyword: the ${word(d)} subsystem`,
      `secondary_keywords: [how the ${word(d)} works, ${word(d + 1)} limits, tuning the ${word(d + 2)}]`,
      `meta_description: How the ${word(d)} subsystem works, what it costs to run, and the three settings that matter when you tune it for a large deployment.`,
      `canonical_url: https://example.com/document-${d}`,
      'updated_date: 2026-08-22',
      '---',
      '',
      `# Document ${d} about the ${word(d)} subsystem`,
      '',
      `The ${word(d)} subsystem holds ${held} items and evicts the oldest first. Everything else follows from that.`,
      '',
    ];

    for (let s = 0; s < 6; s += 1) {
      lines.push(`## How the ${word(d + s)} handles ${word(d + s + 1)} pressure`, '');
      lines.push(`The ${word(d + s)} supports ${s + 3} modes and only one is on by default. Most teams never change it.`, '');
      lines.push(`Every request goes through the same ${word(d + s + 2)}, and the new path is faster than the old one by a factor of ${s + 2}.`, '');
      if (s === 0) lines.push('| Setting | Default |', '| --- | ---: |', `| ${word(d)} | ${d % 64} |`, '');
      if (s === 1) lines.push('```js', `const limit = pLimit(${s + 4});`, '```', '');
      if (s === 2) lines.push(`![a diagram of the ${word(d)} pipeline with ${s + 2} stages](/img/d.png)`, '');
      if (s === 3) lines.push(`See [the guide](/guides/${word(d)}) and [upstream](https://example.org/${word(d)}).`, '');
    }

    lines.push('### Frequently asked', '');
    for (let q = 0; q < 4; q += 1) {
      lines.push(`**Does the ${word(d + q)} need tuning?** Not for most deployments. The default holds until you pass a hundred nodes, at which point the ${word(d + q + 1)} becomes the limit and you raise it once.`, '');
    }

    const body = lines.join('\n');
    words += body.split(/\s+/).length;
    writeFileSync(path.join(dir, 'docs', `doc-${id}.md`), body, 'utf8');
    writeFileSync(
      path.join(dir, 'sources', `fact-${id}.md`),
      `The ${word(d)} subsystem holds ${held} items and evicts the oldest first.\nThe ${word(d)} supports 3 modes.\n`,
      'utf8',
    );
    writeFileSync(
      path.join(dir, 'groundtruth', 'spans', `docs-doc-${id}.mjs`),
      [
        `export const document = ${JSON.stringify(`docs/doc-${id}.md`)};`,
        "export const audited = '2026-08-22';",
        'export const spans = [',
        `  { match: ${JSON.stringify(`The ${word(d)} subsystem holds ${held} items and evicts the oldest first`)}, source: ${JSON.stringify(`facts:fact-${id}.md`)}, quote: ${JSON.stringify(`The ${word(d)} subsystem holds ${held} items and evicts the oldest first.`)}, verdict: 'VERIFIED' },`,
        "  { match: 'Most teams never change it', source: null, quote: null, verdict: 'UNSOURCED', note: 'consensus claim' },",
        '];',
        '',
      ].join('\n'),
      'utf8',
    );
  }

  writeFileSync(path.join(dir, 'groundtruth.config.mjs'), [
    '// Generated by scripts/bench.mjs. No imports, so it loads anywhere.',
    'export default {',
    "  sources: [{ type: 'local', id: 'facts', root: './sources' }],",
    '  profiles: { all: {',
    "    grounding: { enabled: true, spanMaps: 'groundtruth/spans/${docId}.mjs', onDuplicateMatch: 'first' },",
    '    readability: { enabled: true, images: { requireFileExists: false } },',
    "    seo: { enabled: true, preset: 'longform', overrides: { bodyWordsMin: 400, h2Min: 5, secondaryMin: 3 } },",
    '  } },',
    "  documents: [{ include: ['docs/**/*.md'], profile: 'all' }],",
    '};',
    '',
  ].join('\n'), 'utf8');

  return { words, spans: count * 2 };
}

function time(args) {
  const started = process.hrtime.bigint();
  try {
    execFileSync(process.execPath, [bin, ...args], {
      cwd: dir,
      stdio: 'ignore',
      env: { ...process.env, NO_COLOR: '1' },
    });
  } catch {
    // A non-zero exit is expected: the corpus has unsourced claims by design.
  }
  return Number(process.hrtime.bigint() - started) / 1e6;
}

const built = build();
console.log(`corpus: ${count} documents, ${built.words.toLocaleString()} words, ${built.spans} spans\n`);

const runs = [
  ['check --module readability', ['check', '--module', 'readability', '--json']],
  ['check --module seo', ['check', '--module', 'seo', '--json']],
  ['check --module grounding', ['check', '--module', 'grounding', '--json']],
  ['check, all three', ['check', '--json']],
  ['check one document', ['check', 'docs/doc-0000.md', '--json']],
  ['report', ['report']],
];

for (const [label, args] of runs) {
  // Two passes, report the second, so module loading is not counted twice.
  time(args);
  const ms = time(args);
  const per = label.startsWith('check one') ? '' : `  (${(ms / count).toFixed(2)} ms per document)`;
  console.log(`  ${label.padEnd(28)} ${Math.round(ms).toString().padStart(5)} ms${per}`);
}

const reportDir = path.join(dir, '.groundtruth', 'report');
if (existsSync(reportDir)) {
  const files = readdirSync(reportDir);
  const bytes = files.reduce((sum, name) => sum + readFileSync(path.join(reportDir, name)).length, 0);
  const linked = files.includes('report.css');
  console.log(`\n  report: ${files.length} files, ${(bytes / 1e6).toFixed(1)} MB, assets ${linked ? 'shared' : 'inlined'}`);
}

console.log(`\nCorpus left in ${path.relative(process.cwd(), dir)}. It is gitignored.`);
